service: finance-service-accounts

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-dynamodb-local
  - serverless-bundle
  - serverless-pseudo-parameters

# Create an optimized package for our functions
package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  tracing: 
    apiGateway: true
    lambda: true
  
  environment:
    ACCOUNTS_TABLE: ${self:provider.stage}-DB-FS-Accounts
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource:
        - 'Fn::ImportValue': ${self:provider.stage}-DB-FS-AccountsArn

functions:
  createAccount:
    handler: handlers/create.handler
    events:
      - http:
          path: /accounts
          method: post
          cors: true
  removeAccount:
    handler: handlers/remove.handler
    events:
      - http:
          path: /accounts/{id}
          method: delete
          cors: true
  updateAccount: 
    handler: handlers/update.handler
    events:
      - http:
          path: /accounts/{id}
          method: put
          cors: true
  findAccounts: 
    handler: handlers/find.handler
    events:
      - http:
          path: /accounts/{id}
          method: post
          cors: true
