service: users

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-dynamodb-local

# Create an optimized package for our functions
package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: local
  region: 'us-east-1'
  tracing: 
    apiGateway: true
    lambda: true

  environment:
    USERS_TABLE: ${self:provider.stage}-Users

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - 'Fn::ImportValue': ${self:provider.stage}-UsersArn

functions:
  createUser:
    handler: handlers/create.createUser
    events:
      - http:
          path: /users
          method: post
          cors: true
