service: finance-service-users

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-bundle

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  tracing: 
    apiGateway: true
    lambda: true

  environment:
    USERS_TABLE: ${self:provider.stage}-DB-FS-Users

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource:
        - 'Fn::ImportValue': ${self:provider.stage}-DB-FS-UsersArn

functions:
  createUser:
    handler: handlers/create.handler
    events:
      - http:
          path: /users
          method: post
          cors: true
  updateUser: 
    handler: handlers/update.handler
    events:
      - http:
          path: /users/{id}
          method: put
          cors: true
  signIn:
    handler: handlers/signIn.handler
    events:
      - http:
          path: /users/signin
          method: post
          cors: true
  retrieve: 
    handler: handlers/retrieve.handler
    events:
      - http:
          path: /users/{id}
          method: get
          cors: true
