service: database-finance-service

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

package:
  excludeDevDependencies: true
  individually: true

plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true
      noStart: true
      seed: true
      port: 4566
    seed:
      finance:
        sources:
          - table: ${self:provider.stage}-DB-FS-Users
            sources: ["../seed/users.json"]
          - table: ${self:provider.stage}-DB-FS-Accounts
            sources: ["../seed/accounts.json"]
          - table: ${self:provider.stage}-DB-FS-Transactions
            sources: ["../seed/transactions.json"]

resources:
  Resources:
    Users: ${file(tables/users.yml):Users}
    Accounts: ${file(tables/accounts.yml):Accounts}
    Transactions: ${file(tables/transactions.yml):Transactions}

  Outputs:
    UsersArn:
      Value:
        Fn::GetAtt:
          - Users
          - Arn
      Export:
        Name: ${self:provider.stage}-DB-FS-UsersArn
    AccountsArn:
      Value:
        Fn::GetAtt:
          - Accounts
          - Arn
      Export:
        Name: ${self:provider.stage}-DB-FS-AccountsArn
    TransactionsArn:
      Value:
        Fn::GetAtt:
          - Transactions
          - Arn
      Export:
        Name: ${self:provider.stage}-DB-FS-TransactionsArn
