service: database-finance-service

frameworkVersion: "2"

plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      noStart: true
      port: 4566 

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

resources:
  Resources:
    Users: ${file(tables/users.yml):Users}
  
  Outputs:
    UsersArn:
      Value:
        Fn::GetAtt: 
          - Users
          - Arn
      Export:
        Name: ${self:provider.stage}-DB-FS-UsersArn